ankiety/ankieta/urls.py
from django.urls import path

from . import views

app_name = 'ankieta'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.SzczegolyView.as_view(), name='szczegoly'),
    path('<int:pk>/wyniki', views.WynikiView.as_view(), name='wyniki'),
    path('<int:pytanie_id>/glos', views.glos, name='glos'),
]

ankiety/ankiety/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ankieta/', include('ankieta.urls')),
    path('admin/', admin.site.urls),
]

ankiety/ankieta/models.py
import datetime

from django.db import models
from django.utils import timezone

class Pytanie(models.Model):
    pytanie_tekst = models.CharField("treść pytania", max_length=200)
    pub_data = models.DateTimeField('data publikacji')

    def __str__(self):
        """reprezentacja obiektu"""
        return self.pytanie_tekst

    def opublikowane_ostatnio(self):
        teraz = timezone.now()
        return teraz - datetime.timedelta(days=1) <= self.pub_data <= teraz

    opublikowane_ostatnio.admin_order_field = 'pub_data'
    opublikowane_ostatnio.boolean = True
    opublikowane_ostatnio.short_description = 'Opublikowane ostatnio?'

    def ma_odpowiedzi(self):
        return self.odpowiedz_set.all().count()


    class Meta:
        ordering = ['pub_data']
        verbose_name_plural = "pytania"


class Odpowiedz(models.Model):
    pytanie = models.ForeignKey(Pytanie, on_delete=models.CASCADE)
    wybor_tekst = models.CharField("treść odpowiedzi", max_length=200)
    glosy = models.IntegerField(default=0)

    def __str__(self):
        return self.wybor_tekst


    class Meta:
        verbose_name_plural = "odpowiedzi"

ankiety/ankieta/views.py
# from django.http import Http404
from django.shortcuts import get_object_or_404, render
# from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
# from django.template import loader
from django.views import generic
from django.utils import timezone

from .models import Pytanie, Odpowiedz


class IndexView(generic.ListView):
    """Zwraca 5 ostatnio opublikowanych ankiet (bez ankiet opublikowanych w przyszłości)"""
    template_name = 'ankieta/index.html'
    context_object_name = 'ostatnie_pytania_lista'

    def get_queryset(self):
        """Zwraca 5 ostatnio opublikowanych ankiet"""
        return Pytanie.objects.filter(
            pub_data__lte=timezone.now(),
            odpowiedz__isnull=False
        ).distinct().order_by('-pub_data')[:5]


class SzczegolyView(generic.DetailView):
    model = Pytanie
    template_name = 'ankieta/szczegoly.html'

    def get_queryset(self):
       """
       Wykluczenie wszystkich nieopublikowanych jeszcze pytań
       """
       return Pytanie.objects.filter(pub_data__lte=timezone.now())


class WynikiView(generic.DetailView):
    model = Pytanie
    template_name = 'ankieta/wyniki.html'

    def get_queryset(self):
       """
       Wykluczenie wszystkich nieopublikowanych jeszcze pytań
       """
       return Pytanie.objects.filter(pub_data__lte=timezone.now())

def glos(request, pytanie_id):
    pytanie = get_object_or_404(Pytanie, pk=pytanie_id)
    try:
        wybrana_odpowiedz = pytanie.odpowiedz_set.get(pk=request.POST['odpowiedz'])
    except (KeyError, Odpowiedz.DoesNotExist):
        # Redisplay the pytanie voting form.
        return render(request, 'ankieta/szczegoly.html', {
            'pytanie': pytanie,
            'blad_tekst': "Nie wybrałeś odpowiedzi.",
        })
    else:
        wybrana_odpowiedz.glosy += 1
        wybrana_odpowiedz.save()
        # Zawsze zwracaj HttpResponseRedirect po poprawnym obsłużeniu żądania POST
        # z danymi. Zapobiega to dwukrotnemu przesyłaniu danych, gdyby użytkownik
        # nacisnął przycisk wstecz.
        return HttpResponseRedirect(reverse('ankieta:wyniki', args=(pytanie.id,)))

ankiety/ankieta/templates/ankieta/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ankieta/css/style.css' %}" />

{% if ostatnie_pytania_lista %}
    <ul>
    {% for pytanie in ostatnie_pytania_lista %}
        <li><a href="{% url 'ankieta:szczegoly' pytanie.id %}">{{ pytanie.pytanie_tekst }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Brak ankiet.</p>
{% endif %}

ankiety/ankieta/templates/ankieta/szczegoly.html
<h1>{{ pytanie.pytanie_tekst }}</h1>

{% if blad_tekst %}<p><strong>{{ blad_tekst }}</strong></p>{% endif %}

<ul>
{% for odpowiedz in pytanie.odpowiedz_set.all %}
    <li>{{ odpowiedz.wybor_tekst }}</li>
{% endfor %}
</ul>
<form action="{% url 'ankieta:glos' pytanie.id %}" method="post">
{% csrf_token %}
{% for odpowiedz in pytanie.odpowiedz_set.all %}
    <input type="radio" name="odpowiedz" id="odpowiedz{{ forloop.counter }}" value="{{ odpowiedz.id }}" />
    <label for="odpowiedz{{ forloop.counter }}">{{ odpowiedz.wybor_tekst }}</label><br />
{% endfor %}
<input type="submit" value="Glos" />
</form>

ankiety/ankieta/templates/ankieta/wyniki.html
<h1>{{ pytanie.pytanie_tekst }}</h1>

<ul>
{% for odpowiedz in pytanie.odpowiedz_set.all %}
    <li>{{ odpowiedz.wybor_tekst }} -- {{ odpowiedz.glosy }} głos{{ odpowiedz.glosy|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'ankieta:szczegoly' pytanie.id %}">Głosujesz jeszcze raz?</a>